### ISSUE TITLE
exporting error

### ISSUE THREAD

**Issue by nikhil003** [kjellmf/svg2tikz#24] opened 2015-04-11 15:21 UTC
Traceback (most recent call last):
  File "tikz_export.py", line 1433, in <module>
    main_inkscape()
  File "tikz_export.py", line 1417, in main_inkscape
    effect.affect()
  File "C:\Program Files\Inkscape\share\extensions\inkex.py", line 265, in affect
    self.getposinlayer()
  File "C:\Program Files\Inkscape\share\extensions\inkex.py", line 207, in getposinlayer
    x = self.unittouu( xattr[0] + 'px' )
  File "C:\Program Files\Inkscape\share\extensions\inkex.py", line 351, in unittouu
    return retval * (self.__uuconv[u.string[u.start():u.end()]] / self.__uuconv[self.getDocumentUnit()])
  File "C:\Program Files\Inkscape\share\extensions\inkex.py", line 304, in getDocumentUnit
    p = param.match(svgwidth)
TypeError: expected string or buffer

**Comment by kjellmf** [comment] 2015-04-11 16:38
Which version of Inkscape are you using?
Does this happen for every SVG you try?

**Comment by nikhil003** [comment] 2015-04-11 20:41
I am using Inkscape 0.91 on windows machine. I tried coupled of svg files and i got error for both of them..i even tried to see if the command line will work but with my python installation, it gave me same error

**Comment by kjellmf** [comment] 2015-04-12 07:14
I'll try to reproduce the error.

**Comment by OVivero** [comment] 2015-05-06 10:35
I am having the same issue on Inkscape 0.91 on a windows machine. At first I thought the layering of the svg was the issue, so I created a new file with a couple of rectangles and attempted the export. Got the same error:

Traceback (most recent call last):
  File "tikz_export.py", line 1433, in <module>
    main_inkscape()
  File "tikz_export.py", line 1417, in main_inkscape
    effect.affect()
  File "C:\Program Files\Inkscape\share\extensions\inkex.py", line 269, in affect
    if output: self.output()
  File "tikz_export.py", line 1358, in output
    f = codecs.open(self.options.outputfile, 'w', 'utf8')
  File "C:\Program Files\Inkscape\python\Lib\codecs.py", line 870, in open
    file = __builtin__.open(filename, mode, buffering)
IOError: [Errno 13] Permission denied: 'PEL.tex'

**Comment by Mechasaurus** [comment] 2015-05-15 17:33
Hello, 

I've been struggling with the same issue. Haven't been able to export anything at all.

**Comment by kjellmf** [comment] 2015-05-16 16:21
I'm really sorry, but I'm not able to reproduce the issue.  Here is what I tried:

1. I downloaded Inkscape 0.91 from https://inkscape.org/en/download/windows/ I used the binary archives (7z) version 
2. Unpacked the archive to a folder. In my case: `e:\gtools\inkscape `
3. Downloaded the master version of svg2tikz (https://github.com/kjellmf/svg2tikz/archive/master.zip) and unpacked it.
4. Navigated to `svg2tikz\svg2tikz\extensions` and copied  the files `tikz_export.py`,  `tikz_export_effect.inx` and `tikz_export_output.inx` to `e:\gtools\inkscape\share\extensions`
5. Started `e:\gtools\inkscape\inkscape.exe`

You should now find the extension in the menu:
![image](https://cloud.githubusercontent.com/assets/29217/7666929/2634f0a2-fbf8-11e4-8851-7ed9813bd3bf.png)

Hope this helps.

**Comment by Mechasaurus** [comment] 2015-05-16 20:49
Does it matter is you have different version of python installed on your system..? I have python34 in my "PATH" (the environment variables)..

**Comment by Mechasaurus** [comment] 2015-05-16 20:50
Still not working, by the way..

**Comment by kjellmf** [comment] 2015-05-16 21:06
Inkscape comes bundled with Python, so the Python on the path should not matter. Never tested this though. Worth a try. Does any of the other extensions work?

**Comment by kjellmf** [comment] 2015-05-17 16:06
@nikhil003 Looking closer at the traceback I see that the error is raised in `inkex.py`, which is bundled with Inkscape. Do you have Python 3 installed on your system? I know that inkex.py is not compatible with Python 3. As explained above, Inkscape should use the bundled Python 2.7, but I'm starting to suspect that this is not the case.

**Comment by OVivero** [comment] 2015-05-18 07:54
I also had python34 in my system. I uninstalled, together with my existing version of inkscape. Followed your installation instructions and I got the export option under the extensions menu item. However, the export failed as before. Here is the traceback

Traceback (most recent call last):
  File "tikz_export.py", line 1439, in <module>
    main_inkscape()
  File "tikz_export.py", line 1423, in main_inkscape
    effect.affect()
  File "C:\Program Files (x86)\Inkscape\share\extensions\inkex.py", line 269, in affect
    if output: self.output()
  File "tikz_export.py", line 1362, in output
    f = codecs.open(self.options.outputfile, 'w', 'utf8')
  File "C:\Program Files (x86)\Inkscape\python\Lib\codecs.py", line 870, in open
    file = __builtin__.open(filename, mode, buffering)
IOError: [Errno 13] Permission denied: '2PELtex.tex'

**Comment by kjellmf** [comment] 2015-05-18 08:05
@OVivero This looks like a different type of error. From the traceback it looks that the plugin is trying to save 2PELtex.tex to a place where it has no write access. Try entering a full path name, for instance `c:\tmp\2PELtex.tex`. You can also try to use the clipboard option and see if something is added to the clipboard.

**Comment by OVivero** [comment] 2015-05-18 08:49
You are absolutely right, I entered the full path and the export works. Thanks for this!

**Comment by kjellmf** [comment] 2015-06-08 16:19
I'm closing this issue now.

**Closed by kjellmf** 2015-06-08 16:19 UTC

**Comment by Moini** [comment] 2016-09-20 01:39
Btw. this is a known bug: https://bugs.launchpad.net/inkscape/+bug/1463623
